-- =============================================================================
-- BASELINE SCHEMA — CRM 4DPF
-- Pełny snapshot schematu public wygenerowany 2026-07-09 z działającej bazy.
-- Odtwarza od zera: sekwencje, tabele, ograniczenia, indeksy, funkcje, RLS + polityki.
--
-- Uwagi:
--  * auth.users / auth.uid() pochodzą z Supabase Auth (GoTrue) — nie tworzymy ich tutaj.
--  * RLS: wszystkie tabele mają polityki dla roli `authenticated`. n8n/QUO piszą przez
--    service_role (omija RLS). Anon nie ma dostępu do danych.
--  * Ten plik zastępuje wcześniejsze migracje cząstkowe (grafik_pracy, profiles_read_all,
--    sales_shifts) — patrz uwaga przy commicie.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. SEKWENCJE (tylko realnie używane; kolumny id to w większości IDENTITY)
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public."Products_id_seq";

-- ---------------------------------------------------------------------------
-- 2. TABELE
-- ---------------------------------------------------------------------------
CREATE TABLE public."Clients" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    phone text,
    phone_alt text,
    client_name text,
    company text,
    email text,
    location text,
    vat_no text,
    assigned_salesman text,
    source text,
    notes text
);

CREATE TABLE public."Hardware" (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    component_type text NOT NULL,
    name text NOT NULL,
    stock_qty integer NOT NULL DEFAULT 0,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    program text
);

CREATE TABLE public."Machine Issues" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    model text,
    year integer,
    problem text
);

CREATE TABLE public."Machines" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    brand text,
    model text,
    year numeric,
    engine text,
    displacement text,
    serial_number text,
    dpf boolean,
    def boolean,
    can_speed numeric,
    emulator text,
    harness text,
    straight_pipe text,
    return_status text
);

CREATE TABLE public."OLX" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    olx_id numeric NOT NULL,
    name text,
    "position" text,
    education numeric,
    language numeric,
    experience numeric,
    grade numeric,
    cv_name text,
    cv_url text,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public."Opinie" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    technik text,
    contact text,
    channel text,
    napisano boolean DEFAULT false,
    napisac boolean DEFAULT false,
    wystawil boolean DEFAULT false,
    google_name text
);

CREATE TABLE public."Products" (
    id integer NOT NULL DEFAULT nextval('"Products_id_seq"'::regclass),
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    category text,
    stock_qty integer NOT NULL DEFAULT 0,
    price_default numeric,
    notes text,
    plytka text,
    program text,
    obudowa text
);

CREATE TABLE public."Sales" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    salesman text,
    email_address text,
    phone text,
    sale_status text,
    shipping_details text,
    invoice_details text,
    tracking_number text,
    paypal_invoice_number text,
    company text,
    machine_id numeric,
    client_name text,
    location text,
    price numeric,
    shipping_cost numeric,
    total numeric,
    quantity integer DEFAULT 1,
    payment_method text,
    first_contact text,
    vat_no text,
    deal_id integer,
    pipe_type text,
    zestaw_id integer,
    notes text,
    client_id bigint
);

CREATE TABLE public."Sales Deals" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    status text,
    phone text,
    salesman text,
    category text,
    last_contact_at timestamp with time zone,
    current_summary text,
    detected_engine text,
    email text,
    shipping_details text,
    client_name text
);

CREATE TABLE public."Sales Items" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    sale_id bigint NOT NULL,
    zestaw_id bigint,
    quantity integer NOT NULL DEFAULT 1,
    price numeric(10,2)
);

CREATE TABLE public."Sales Quality" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    salesman text,
    category text,
    rating numeric,
    phone text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    clients_name text,
    feedback text,
    detected_engine text,
    summary text,
    email text,
    shipping_details text,
    duration numeric,
    update text,
    full_transcript text,
    deal_id numeric
);

CREATE TABLE public."Sales Text Log" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    phone text,
    direction text,
    full_message text,
    summary text,
    media json,
    deal_id numeric,
    category text
);

CREATE TABLE public."Software" (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    product_line text NOT NULL DEFAULT '4DPF'::text,
    name text NOT NULL,
    plytka text,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public."Support Backlog" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    phone text,
    invoice_number text,
    client_name text,
    status text NOT NULL DEFAULT 'open'::text,
    agent text
);

CREATE TABLE public."Support Backlog Log" (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone DEFAULT now(),
    backlog_id bigint NOT NULL,
    agent text,
    problem text,
    proposed_solution text,
    outcome text,
    notes text
);

CREATE TABLE public."Support Case" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    phone text,
    clients_name text,
    status text,
    last_contact_at timestamp with time zone DEFAULT now(),
    last_agent text,
    current_category text,
    current_problem_summary text,
    current_recommendations text,
    last_interaction_id numeric,
    detected_engine text,
    final_resolution text
);

CREATE TABLE public."Support Log" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    support_agent text,
    category text,
    phone text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    clients_name text,
    detected_engine text,
    summary text,
    email text,
    duration numeric,
    problem_description text,
    support_recommendations text,
    full_transcript text,
    case_id numeric
);

CREATE TABLE public."Support Text Log" (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    phone text,
    summary text,
    media json,
    full_message text,
    case_id numeric,
    direction text
);

CREATE TABLE public."Wiazki" (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    emulator text,
    name text NOT NULL,
    stock_qty integer NOT NULL DEFAULT 0,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    product_line text NOT NULL DEFAULT '4DPF'::text
);

CREATE TABLE public."Zestawy" (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nr integer NOT NULL,
    name text NOT NULL,
    emulator_program text,
    wiazka text,
    notes text,
    instrukcja text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    price numeric,
    price_currency text DEFAULT 'USD'::text
);

CREATE TABLE public.activity_logs (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id uuid,
    user_email text,
    action text NOT NULL,
    tab_key text NOT NULL,
    record_id text,
    details text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.availability (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    work_date date NOT NULL,
    department text NOT NULL,
    kind text NOT NULL DEFAULT 'available'::text,
    shift_pref bigint,
    note text
);

CREATE TABLE public.calls (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    quo_call_id text,
    created_at timestamp with time zone DEFAULT now(),
    phone text,
    direction text,
    status text DEFAULT 'ringing'::text,
    duration_seconds integer,
    recording_url text,
    quo_user_id text,
    answered_by_name text,
    is_known_client boolean DEFAULT false,
    client_id bigint,
    client_name text,
    notes text,
    machine_interest text,
    lead_created boolean DEFAULT false,
    handled boolean DEFAULT false
);

CREATE TABLE public.domains (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    domain text,
    provider text,
    due_date timestamp with time zone
);

CREATE TABLE public.hostings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    description text,
    provider text,
    due_date timestamp with time zone
);

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    role text NOT NULL DEFAULT 'handlowiec'::text,
    full_name text,
    created_at timestamp with time zone DEFAULT now(),
    is_lead boolean NOT NULL DEFAULT false
);

CREATE TABLE public.schedule_entries (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    work_date date NOT NULL,
    shift_type_id bigint,
    department text NOT NULL,
    status text NOT NULL DEFAULT 'draft'::text,
    note text,
    created_by uuid
);

CREATE TABLE public.shift_swaps (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    department text NOT NULL,
    requester_id uuid NOT NULL,
    requester_entry_id bigint NOT NULL,
    target_id uuid NOT NULL,
    target_entry_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'pending'::text,
    resolved_by uuid,
    resolved_at timestamp with time zone
);

CREATE TABLE public.shift_types (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    department text NOT NULL,
    name text NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    color text
);

CREATE TABLE public.tab_permissions (
    role text NOT NULL,
    tab_key text NOT NULL,
    can_view boolean NOT NULL DEFAULT true,
    can_write boolean NOT NULL DEFAULT true,
    can_edit boolean NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------------
-- 3. OGRANICZENIA (PK, UNIQUE, CHECK, FK)
-- ---------------------------------------------------------------------------
ALTER TABLE public."Clients" ADD CONSTRAINT "Clients_pkey" PRIMARY KEY (id);

ALTER TABLE public."Hardware" ADD CONSTRAINT "Hardware_pkey" PRIMARY KEY (id);
ALTER TABLE public."Hardware" ADD CONSTRAINT "Hardware_component_type_check" CHECK ((component_type = ANY (ARRAY['płytka surowa'::text, 'płytka zaprogramowana'::text, 'obudowa'::text])));

ALTER TABLE public."Machine Issues" ADD CONSTRAINT "Machine Issues_pkey" PRIMARY KEY (id);

ALTER TABLE public."Machines" ADD CONSTRAINT "Machines_pkey" PRIMARY KEY (id);

ALTER TABLE public."OLX" ADD CONSTRAINT "OLX_pkey" PRIMARY KEY (id);

ALTER TABLE public."Opinie" ADD CONSTRAINT "Opinie_pkey" PRIMARY KEY (id);

ALTER TABLE public."Products" ADD CONSTRAINT "Products_pkey" PRIMARY KEY (id);

ALTER TABLE public."Sales" ADD CONSTRAINT "Sales_pkey" PRIMARY KEY (id);
ALTER TABLE public."Sales" ADD CONSTRAINT "Sales_product_id_fkey" FOREIGN KEY (zestaw_id) REFERENCES public."Products"(id);
ALTER TABLE public."Sales" ADD CONSTRAINT "Sales_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public."Clients"(id);

ALTER TABLE public."Sales Deals" ADD CONSTRAINT "Sale Log_pkey" PRIMARY KEY (id);

ALTER TABLE public."Sales Items" ADD CONSTRAINT "Sales Items_pkey" PRIMARY KEY (id);
ALTER TABLE public."Sales Items" ADD CONSTRAINT "Sales Items_sale_id_fkey" FOREIGN KEY (sale_id) REFERENCES public."Sales"(id) ON DELETE CASCADE;
ALTER TABLE public."Sales Items" ADD CONSTRAINT "Sales Items_zestaw_id_fkey" FOREIGN KEY (zestaw_id) REFERENCES public."Zestawy"(id) ON DELETE SET NULL;

ALTER TABLE public."Sales Quality" ADD CONSTRAINT "Sales Quality_pkey" PRIMARY KEY (id);

ALTER TABLE public."Sales Text Log" ADD CONSTRAINT "Sales Text Log_pkey" PRIMARY KEY (id);

ALTER TABLE public."Software" ADD CONSTRAINT "Software_pkey" PRIMARY KEY (id);

ALTER TABLE public."Support Backlog" ADD CONSTRAINT "Support Backlog_pkey" PRIMARY KEY (id);

ALTER TABLE public."Support Backlog Log" ADD CONSTRAINT "Support Backlog Log_pkey" PRIMARY KEY (id);
ALTER TABLE public."Support Backlog Log" ADD CONSTRAINT "Support Backlog Log_backlog_id_fkey" FOREIGN KEY (backlog_id) REFERENCES public."Support Backlog"(id) ON DELETE CASCADE;

ALTER TABLE public."Support Case" ADD CONSTRAINT "Support Case_pkey" PRIMARY KEY (id);

ALTER TABLE public."Support Log" ADD CONSTRAINT "Support Quality_pkey" PRIMARY KEY (id);

ALTER TABLE public."Support Text Log" ADD CONSTRAINT "Support Text Log_pkey" PRIMARY KEY (id);

ALTER TABLE public."Wiazki" ADD CONSTRAINT "Wiazki_pkey" PRIMARY KEY (id);

ALTER TABLE public."Zestawy" ADD CONSTRAINT "Zestawy_pkey" PRIMARY KEY (id);
ALTER TABLE public."Zestawy" ADD CONSTRAINT "Zestawy_nr_key" UNIQUE (nr);

ALTER TABLE public.activity_logs ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);

ALTER TABLE public.availability ADD CONSTRAINT availability_pkey PRIMARY KEY (id);
ALTER TABLE public.availability ADD CONSTRAINT availability_user_id_work_date_key UNIQUE (user_id, work_date);
ALTER TABLE public.availability ADD CONSTRAINT availability_kind_check CHECK ((kind = ANY (ARRAY['available'::text, 'unavailable'::text, 'preferred'::text])));
ALTER TABLE public.availability ADD CONSTRAINT availability_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.availability ADD CONSTRAINT availability_shift_pref_fkey FOREIGN KEY (shift_pref) REFERENCES public.shift_types(id) ON DELETE SET NULL;

ALTER TABLE public.calls ADD CONSTRAINT calls_pkey PRIMARY KEY (id);
ALTER TABLE public.calls ADD CONSTRAINT calls_quo_call_id_key UNIQUE (quo_call_id);

ALTER TABLE public.domains ADD CONSTRAINT domains_pkey PRIMARY KEY (id);

ALTER TABLE public.hostings ADD CONSTRAINT hostings_pkey PRIMARY KEY (id);

ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_user_id_work_date_key UNIQUE (user_id, work_date);
ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text])));
ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_shift_type_id_fkey FOREIGN KEY (shift_type_id) REFERENCES public.shift_types(id) ON DELETE SET NULL;
ALTER TABLE public.schedule_entries ADD CONSTRAINT schedule_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_pkey PRIMARY KEY (id);
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'approved'::text, 'cancelled'::text])));
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_requester_entry_id_fkey FOREIGN KEY (requester_entry_id) REFERENCES public.schedule_entries(id) ON DELETE CASCADE;
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_target_entry_id_fkey FOREIGN KEY (target_entry_id) REFERENCES public.schedule_entries(id) ON DELETE CASCADE;
ALTER TABLE public.shift_swaps ADD CONSTRAINT shift_swaps_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.shift_types ADD CONSTRAINT shift_types_pkey PRIMARY KEY (id);

ALTER TABLE public.tab_permissions ADD CONSTRAINT tab_permissions_pkey PRIMARY KEY (role, tab_key);

-- ---------------------------------------------------------------------------
-- 4. INDEKSY (poza tworzonymi przez ograniczenia)
-- ---------------------------------------------------------------------------
CREATE INDEX availability_user_date_idx ON public.availability USING btree (user_id, work_date);
CREATE INDEX availability_dept_date_idx ON public.availability USING btree (department, work_date);
CREATE INDEX schedule_entries_user_idx ON public.schedule_entries USING btree (user_id);
CREATE INDEX schedule_entries_dept_date_idx ON public.schedule_entries USING btree (department, work_date);
CREATE INDEX shift_swaps_dept_status_idx ON public.shift_swaps USING btree (department, status);
CREATE INDEX shift_swaps_target_idx ON public.shift_swaps USING btree (target_id);
CREATE INDEX shift_swaps_requester_idx ON public.shift_swaps USING btree (requester_id);
CREATE INDEX shift_types_department_idx ON public.shift_types USING btree (department);

-- ---------------------------------------------------------------------------
-- 5. FUNKCJE POMOCNICZE (RLS Grafik) — po tabelach, bo odwołują się do profiles
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.my_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT role FROM public.profiles WHERE id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.my_is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(role = 'admin', false) FROM public.profiles WHERE id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.my_is_lead()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(is_lead, false) FROM public.profiles WHERE id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.can_manage_department(dept text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  SELECT public.my_is_admin()
      OR (public.my_is_lead() AND public.my_role() = dept)
$function$;

-- ---------------------------------------------------------------------------
-- 6. WŁĄCZENIE RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public."Clients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Hardware" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Machine Issues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Machines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OLX" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Opinie" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Sales Deals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Sales Items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Sales Quality" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Sales Text Log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Software" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Support Backlog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Support Backlog Log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Support Case" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Support Log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Support Text Log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Wiazki" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Zestawy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hostings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_swaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tab_permissions ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 7. POLITYKI RLS
--    Wszystkie tabele danych: dostęp dla roli `authenticated`.
--    uid() -> auth.uid(); funkcje pomocnicze kwalifikowane public.*
-- ---------------------------------------------------------------------------
CREATE POLICY authenticated_all ON public."Clients" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY hardware_select ON public."Hardware" FOR SELECT TO authenticated USING (true);
CREATE POLICY hardware_insert ON public."Hardware" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY hardware_update ON public."Hardware" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY hardware_delete ON public."Hardware" FOR DELETE TO authenticated USING (true);

CREATE POLICY authenticated_all_machine_issues ON public."Machine Issues" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Machines" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."OLX" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all_opinie ON public."Opinie" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Products" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Sales" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Sales Deals" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Sales Items" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Sales Quality" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Sales Text Log" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY software_select ON public."Software" FOR SELECT TO authenticated USING (true);
CREATE POLICY software_insert ON public."Software" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY software_update ON public."Software" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY software_delete ON public."Software" FOR DELETE TO authenticated USING (true);

CREATE POLICY authenticated_all_support_backlog ON public."Support Backlog" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all_support_backlog_log ON public."Support Backlog Log" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Support Case" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Support Log" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY authenticated_all ON public."Support Text Log" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY auth_select ON public."Wiazki" FOR SELECT TO authenticated USING (true);
CREATE POLICY auth_insert ON public."Wiazki" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY auth_update ON public."Wiazki" FOR UPDATE TO authenticated USING (true);
CREATE POLICY auth_delete ON public."Wiazki" FOR DELETE TO authenticated USING (true);

CREATE POLICY auth_select ON public."Zestawy" FOR SELECT TO authenticated USING (true);
CREATE POLICY auth_insert ON public."Zestawy" FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY auth_update ON public."Zestawy" FOR UPDATE TO authenticated USING (true);
CREATE POLICY auth_delete ON public."Zestawy" FOR DELETE TO authenticated USING (true);

CREATE POLICY authenticated_read_activity_logs ON public.activity_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY authenticated_insert_activity_logs ON public.activity_logs FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY availability_select ON public.availability FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR public.can_manage_department(department)));
CREATE POLICY availability_write ON public.availability FOR ALL TO authenticated USING ((user_id = auth.uid())) WITH CHECK (((user_id = auth.uid()) AND (department = public.my_role())));

CREATE POLICY authenticated_all ON public.calls FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY allow_authenticated ON public.domains FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY allow_authenticated ON public.hostings FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Users can read own profile" ON public.profiles FOR SELECT TO public USING ((auth.uid() = id));
CREATE POLICY authenticated_read_all_profiles ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY schedule_entries_select ON public.schedule_entries FOR SELECT TO authenticated USING (((department = public.my_role()) OR public.my_is_admin()));
CREATE POLICY schedule_entries_write ON public.schedule_entries FOR ALL TO authenticated USING (public.can_manage_department(department)) WITH CHECK (public.can_manage_department(department));

CREATE POLICY shift_swaps_select ON public.shift_swaps FOR SELECT TO authenticated USING (((requester_id = auth.uid()) OR (target_id = auth.uid()) OR public.can_manage_department(department)));
CREATE POLICY shift_swaps_insert ON public.shift_swaps FOR INSERT TO authenticated WITH CHECK (((requester_id = auth.uid()) AND (department = public.my_role())));
CREATE POLICY shift_swaps_update ON public.shift_swaps FOR UPDATE TO authenticated USING (((requester_id = auth.uid()) OR (target_id = auth.uid()) OR public.can_manage_department(department))) WITH CHECK (((requester_id = auth.uid()) OR (target_id = auth.uid()) OR public.can_manage_department(department)));
CREATE POLICY shift_swaps_delete ON public.shift_swaps FOR DELETE TO authenticated USING (((requester_id = auth.uid()) OR public.can_manage_department(department)));

CREATE POLICY shift_types_select ON public.shift_types FOR SELECT TO authenticated USING (((department = public.my_role()) OR public.my_is_admin()));
CREATE POLICY shift_types_write ON public.shift_types FOR ALL TO authenticated USING (public.can_manage_department(department)) WITH CHECK (public.can_manage_department(department));

CREATE POLICY authenticated_read_tab_permissions ON public.tab_permissions FOR SELECT TO authenticated USING (true);
