-- =============================================================================
-- dump_schema() — zrzut całego schematu `public` jako gotowy tekst .sql
-- =============================================================================
-- Używana przez trasę /api/admin/schema-dump (service_role) → przycisk w panelu
-- admina „Pobierz zrzut schematu".
--
-- Kluczowy trik: SET search_path = pg_catalog. Dzięki temu pg_get_constraintdef /
-- pg_get_expr / pg_policies renderują WSZYSTKIE obiekty spoza pg_catalog z pełną
-- kwalifikacją schematu (auth.uid(), auth.users, public.my_role()) — output jest
-- uruchamialny na czystej bazie bez zależności od search_path.
--
-- Preambuła zrzutu ustawia check_function_bodies = false, więc kolejność funkcji
-- odwołujących się do siebie / do tabel nie ma znaczenia przy odtwarzaniu.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.dump_schema()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog'
AS $dump$
  -- Kolejność: ord → sub → tbl. `sub` PRZED `tbl` jest kluczowe dla ograniczeń
  -- (ord=2): wszystkie PK/UNIQUE (sub 1–2) muszą powstać przed jakimkolwiek FK
  -- (sub=4), bo FK wymaga istniejącego UNIQUE/PK w tabeli docelowej. Przy sortowaniu
  -- po tbl-najpierw FK tabeli „A"→„Z" trafiał przed PK tabeli „Z" i odtwarzanie padało
  -- („no unique constraint matching given keys"). W innych blokach sub=0, więc
  -- kolejność alfabetyczna po tbl zostaje bez zmian.
  SELECT string_agg(ddl, E'\n\n' ORDER BY ord, sub, tbl)
  FROM (
    -- preambuła
    SELECT -1 AS ord, ''::text AS tbl, 0 AS sub,
      '-- Zrzut schematu public — ' || to_char(now(), 'YYYY-MM-DD HH24:MI')
      || E'\nSET check_function_bodies = false;' AS ddl

    UNION ALL
    -- 0) sekwencje (bez wewnętrznych sekwencji kolumn IDENTITY)
    SELECT 0, c.relname, 0,
      'CREATE SEQUENCE IF NOT EXISTS public.' || quote_ident(c.relname) || ';'
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S' AND n.nspname = 'public'
      AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'i')

    UNION ALL
    -- 1) tabele
    SELECT 1, c.relname, 0,
      'CREATE TABLE public.' || quote_ident(c.relname) || E' (\n' ||
      string_agg(
        '    ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
        || CASE
             WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
             WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
             WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
             ELSE ''
           END,
        E',\n' ORDER BY a.attnum
      ) || E'\n);'
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    LEFT JOIN pg_attrdef ad ON ad.adrelid = c.oid AND ad.adnum = a.attnum
    WHERE c.relkind = 'r' AND n.nspname = 'public'
    GROUP BY c.relname

    UNION ALL
    -- 2) ograniczenia (PK, UNIQUE, CHECK, FK)
    SELECT 2, c.relname,
      CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'f' THEN 4 ELSE 5 END,
      'ALTER TABLE public.' || quote_ident(c.relname)
      || ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'

    UNION ALL
    -- 3) indeksy (poza tworzonymi przez ograniczenia)
    SELECT 3, i.tablename, 0, i.indexdef || ';'
    FROM pg_indexes i
    WHERE i.schemaname = 'public'
      AND NOT EXISTS (
        SELECT 1 FROM pg_constraint con
        JOIN pg_class ic ON ic.oid = con.conindid
        WHERE ic.relname = i.indexname
      )

    UNION ALL
    -- 4) funkcje (bez samej dump_schema)
    SELECT 4, p.proname, 0, pg_get_functiondef(p.oid) || ';'
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname <> 'dump_schema'

    UNION ALL
    -- 5) triggery
    SELECT 5, c.relname, 0, pg_get_triggerdef(t.oid) || ';'
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND NOT t.tgisinternal

    UNION ALL
    -- 6) włączenie RLS
    SELECT 6, c.relname, 0,
      'ALTER TABLE public.' || quote_ident(c.relname) || ' ENABLE ROW LEVEL SECURITY;'
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'r' AND n.nspname = 'public' AND c.relrowsecurity

    UNION ALL
    -- 7) polityki RLS
    SELECT 7, p.tablename, 0,
      'CREATE POLICY ' || quote_ident(p.policyname) || ' ON public.' || quote_ident(p.tablename)
      || ' AS ' || p.permissive || ' FOR ' || p.cmd
      || ' TO ' || array_to_string(p.roles, ', ')
      || COALESCE(' USING (' || p.qual || ')', '')
      || COALESCE(' WITH CHECK (' || p.with_check || ')', '') || ';'
    FROM pg_policies p
    WHERE p.schemaname = 'public'
  ) x;
$dump$;

-- Tylko service_role (trasa admina) może wołać — nie anon/authenticated.
REVOKE ALL ON FUNCTION public.dump_schema() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.dump_schema() TO service_role;
